//
//  Copyright 2025-2026 Shuntaro Kasatani
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

mod array_list;
mod array_spread;
mod chain;
mod literal;
mod operator;
mod subscript;

use crate::{
    ast_nodes::{
        CompilationData, Expr, NameSpaceID, ScopeID,
        compilation_data::ProgramContext,
        symbol_table::{UnresolvedExpr, UnresolvedExprKind},
    },
    builtin::BuiltinRegistry,
    error::ErrorCollector,
};

/// Builds an `Expr` with type informations, from the given `UnresolvedExpr` generated by `ExpressionBuilder`.
pub struct ExpressionResolver<'a> {
    ec: &'a mut ErrorCollector,
    prog_ctx: &'a mut ProgramContext,
    comp_data: &'a mut CompilationData,
    builtin_registry: &'a BuiltinRegistry,
    current_scope: ScopeID,
    current_namespace: NameSpaceID,
}

impl<'a> ExpressionResolver<'a> {
    pub fn new(
        ec: &'a mut ErrorCollector,
        prog_ctx: &'a mut ProgramContext,
        comp_data: &'a mut CompilationData,
        builtin_registry: &'a BuiltinRegistry,
        current_scope: ScopeID,
        current_namespace: NameSpaceID,
    ) -> Self {
        Self {
            ec,
            prog_ctx,
            comp_data,
            builtin_registry,
            current_scope,
            current_namespace,
        }
    }

    pub fn resolve_recursively(&mut self, expr: UnresolvedExpr) -> Option<Expr> {
        match expr.kind {
            UnresolvedExprKind::IntLiteral(value) => self.resolve_int_literal(value, expr.range),
            UnresolvedExprKind::FloatLiteral(value) => {
                self.resolve_float_literal(value, expr.range)
            }
            UnresolvedExprKind::BoolLiteral(value) => self.resolve_bool_literal(value, expr.range),

            UnresolvedExprKind::InfixOp {
                symbol,
                lhs_expr,
                rhs_expr,
            } => self.resolve_infix_op(symbol, *lhs_expr, *rhs_expr, expr.range),

            UnresolvedExprKind::PrefixOp { symbol, operand } => {
                self.resolve_prefix_op(symbol, *operand, expr.range)
            }

            UnresolvedExprKind::PostfixOp { symbol, operand } => {
                self.resolve_postfix_op(symbol, *operand, expr.range)
            }

            UnresolvedExprKind::Chain { lhs, elements } => {
                self.resolve_chain(lhs.map(|lhs| *lhs), elements, expr.range)
            }

            UnresolvedExprKind::Subscript { lhs, index } => {
                self.resolve_subscript(*lhs, *index, expr.range)
            }

            UnresolvedExprKind::ArraySpread { value, count } => {
                self.resolve_array_spread(*value, *count, expr.range)
            }

            UnresolvedExprKind::ArrayList(items) => self.resolve_array_list(items, expr.range),
        }
    }
}
