//
// Copyright 2025-2026 Shuntaro Kasatani
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

use crate::{
    ExprToken, ParserSymbolPath, Program, Range, SymbolPath,
    error::Phase,
    resolution::{TypeResolveCtx, expr_inference::ExprTreeBuilder},
    tree_items::variables::VariableTrait,
};

impl<'a> TypeResolveCtx<'a> {
    /// Infer the type of the variable and write it to the Program.
    ///
    /// # Arguments
    /// - `symbol_path`: SymbolPath of the variable to infer type for.
    /// - `decl_range`: Range of the declaration statement.
    /// - `get_target`: Function to get the target variable.
    /// - `default_value`: Default value of the variable in ExprToken.
    /// - `type_annotation`: Type annotation of the variable in ParserSymbolPath.
    pub fn resolve_variable<T, F>(
        &mut self,
        symbol_path: &SymbolPath,
        decl_range: Range,
        get_target: F,
        default_value: Option<&Vec<ExprToken>>,
        type_annotation: Option<&ParserSymbolPath>,
    ) where
        F: for<'b> Fn(&'b mut Program) -> Option<&'b mut T>,
        T: VariableTrait + Sized + std::fmt::Debug,
    {
        if let Some(default_value) = default_value {
            let parsed_expr = match self.program.build_expr_tree_from_raw_tokens(
                self.ec,
                default_value,
                self.symbol_table,
            ) {
                Some(expr) => expr,
                None => return,
            };
            let def_val_type = match parsed_expr.get_type(self.ec, self.program, decl_range) {
                Some(t) => t,
                None => return,
            };

            if let Some(type_annotation) = type_annotation {
                if let Some(annotation_type) =
                    self.program.resolve_type_def_parser_path(type_annotation)
                {
                    // Check if the type annotation matches the inferred type
                    if annotation_type == def_val_type {
                        let target_variable = match get_target(self.program) {
                            Some(target) => target,
                            None => {
                                self.ec.comp_bug(
                                    decl_range,
                                    Phase::TypeResolution,
                                    "Symbol path generated by build_graph() is invalid.",
                                );
                                return;
                            }
                        };
                        target_variable.set_default_value(Some(parsed_expr));
                        target_variable.set_value_type(Some(annotation_type));
                    } else {
                        // If the type annotation doesn't match the inferred type, throw an error
                        self.ec.type_mismatch(
                            decl_range,
                            Phase::TypeResolution,
                            &annotation_type.to_string(),
                            &def_val_type.to_string(),
                        );
                    }
                } else {
                    // If the type annotation is not found, throw an error
                    self.ec.type_not_found(
                        decl_range,
                        Phase::TypeResolution,
                        &type_annotation.to_string(),
                    );
                }
            } else {
                // If the symbol doesn't have a type annotation, use the inferred one
                let target_variable = match get_target(self.program) {
                    Some(target) => target,
                    None => {
                        self.ec.comp_bug(
                            decl_range,
                            Phase::TypeResolution,
                            "Symbol path generated by build_graph() is invalid.",
                        );
                        return;
                    }
                };
                target_variable.set_value_type(Some(def_val_type));
            }
        } else if let Some(type_annotation) = type_annotation {
            if let Some(type_symbol_path) =
                self.program.resolve_type_def_parser_path(type_annotation)
            {
                // If the symbol has a type annotation, use it
                let target_variable = match get_target(self.program) {
                    Some(target) => target,
                    None => {
                        self.ec.comp_bug(
                            decl_range,
                            Phase::TypeResolution,
                            "Symbol path generated by build_graph() is invalid.",
                        );
                        return;
                    }
                };
                target_variable.set_value_type(Some(type_symbol_path));
            } else {
                // If the type annotation is not found, push an error
                self.ec.type_not_found(
                    decl_range,
                    Phase::TypeResolution,
                    &type_annotation.to_string(),
                );
            }
        } else {
            // If the symbol doesn't have the both type annotation and inferred type, push an error
            self.ec.missing_type_annotation(
                decl_range,
                Phase::TypeResolution,
                &symbol_path.to_string(),
            );
        }
    }
}
